### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by lymgoforit** [Fengdalu/Lipreading-DenseNet3D#1]
hello,I can't find the dataset, I am wondering if you could kindly send me the dataset and the necessary information about it. I promise they will be used only for research purposed.Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by liuspencersjtu** [comment]
It seems that you can download it here: http://vipl.ict.ac.cn/view_database.php?id=14, but you need to be a full-time staff member of an University or other research institute.

**Comment by lymgoforit** [comment]
@liuspencersjtu 
thank you. I have got the dataset.

**Comment by Fengdalu** [comment]
Link:  http://vipl.ict.ac.cn/view_database.php?id=14

**Comment by kunshou123** [comment]
hi, i can train the code ,but find loss cannot decrease,Do you have some advice?

**Comment by sunnymoon155** [comment]
@lymgoforit Hi, Did u get the structure of the dataset?

**Comment by birdflies** [comment]
@

> @liuspencersjtu
> thank you. I have got the dataset.

您好，方便分享下数据集吗，谢谢 哈，邮箱97229546@qq.com
