### ISSUE TITLE
when I run “python main.py options_lip.toml” There are the following errors:

### ISSUE THREAD

**Issue by purpletpig** [Fengdalu/Lipreading-DenseNet3D#2]
when I run “python main.py options_lip.toml”
There are the following errors:
Loading options...
Running cudnn benchmark...
matched keys: 431
('index file:', u'/home/liuheng/work/data/LRW-1000/info/tst_1000.txt')
('num of pinyins:', 1000)
('num of data:', 51588)
('max video length', 35)
Starting test...
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    result = tester(model)
  File "/home/liuheng/work/lipReader/LRW-1000_A/Lipreading-DenseNet3D-master/validation.py", line 61, in __call__
    p = list(argmax[i]).index(labels[i])
TypeError: eq() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
 * (Number other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)

**Comment by kunshou123** [comment]
hi, i can train the code ,but find loss cannot decrease,Do you have some advice?

**Comment by purpletpig** [comment]
I chose another implementation
https://github.com/NirHeaven/D3D

**Comment by purpletpig** [comment]
> hi, i can train the code ,but find loss cannot decrease,Do you have some advice?
I chose another implementation
https://github.com/NirHeaven/D3D

**Comment by kunshou123** [comment]
> I chose another implementation
> https://github.com/NirHeaven/D3D
thank you very mach !There's one more question to ask you.Do you know the number of LRW_1000 data sets? because there are 7083 subfolders in images folder after I uncompress it, but there are only 109653 available datas for training, not the 603193 datas shown in the trn_1000.txt. May I ask what is your training data is like that?
