### ISSUE TITLE
请问CUDA out of memory && ValueError: pic should be 2/3 dimensional. Got 0 dimensions.出错

### ISSUE THREAD

**Issue by PingYufeng** [Fengdalu/Lipreading-DenseNet3D#4]
### 一、训练时，报CUDA out of memory，把batchsize改小后可以进入训练，但又出现ValueError: pic should be 2/3 dimensional. Got 0 dimensions的问题，请见下面的 二
Loading options...
Running cudnn benchmark...
options: {'title': 'LipReading PyTorch', 'general': {'usecudnn': True, 'usecudnnbenchmark': True, 'gpuid': '0', 'loadpretrainedmodel': True, 'random_seed': 55, 'pretrainedmodelpath': 'weights/lrw1000_34.pt'}, 'input': {'batchsize': 16, 'numworkers': 8, 'shuffle': True}, 'model': {'type': 'Finetune-label', 'inputdim': 256, 'hiddendim': 256, 'numclasses': 1000, 'numlstms': 2}, 'training': {'train': True, 'epochs': 1, 'startepoch': 0, 'statsfrequency': 100, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/trn_1000.txt', 'padding': 30, 'learningrate': 0.001, 'momentum': 0.9, 'weightdecay': 0.003, 'save_prefix': 'weights/tv_word_2000'}, 'validation': {'validate': True, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/val_1000.txt', 'padding': 60, 'saveaccuracy': True}, 'test': {'test': False, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/tst_1000.txt', 'padding': 60, 'saveaccuracy': True}}
matched keys: 431
index file: LRW1000_Public/info/trn_1000.txt
num of pinyins: 1000
num of data: 603097
max video length 30
index file: LRW1000_Public/info/val_1000.txt
num of pinyins: 1000
num of data: 63237
max video length 51
options["training"]["startepoch"], options["training"]["epochs"]: 0 1
Starting training...
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\envs\py36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Git_Lip\Lipreading-DenseNet3D\main.py", line 119, in run
    trainer(model, epoch)
  File "E:\Git_Lip\Lipreading-DenseNet3D\training.py", line 92, in __call__
    outputs = net(input)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Git_Lip\Lipreading-DenseNet3D\models\Dense3D.py", line 148, in forward
    f2 = self.features(x)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Git_Lip\Lipreading-DenseNet3D\models\Dense3D.py", line 79, in forward
    new_features = super(_DenseLayer, self).forward(x)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\conv.py", line 478, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 1.32 GiB (GPU 0; 11.00 GiB total capacity; 6.81 GiB already allocated; 1.60 GiB free; 25.92 MiB cached)

### 二、把bacth_size改成8后可以训练，报ValueError: pic should be 2/3 dimensional. Got 0 dimensions.
(py36) E:\Git_Lip\Lipreading-DenseNet3D>python main.py options_lip.toml
Loading options...
Running cudnn benchmark...
options: {'title': 'LipReading PyTorch', 'general': {'usecudnn': True, 'usecudnnbenchmark': True, 'gpuid': '0', 'loadpretrainedmodel': True, 'random_seed': 55, 'pretrainedmodelpath': 'weights/lrw1000_34.pt'}, 'input': {'batchsize': 8, 'numworkers': 8, 'shuffle': True}, 'model': {'type': 'Finetune-label', 'inputdim': 256, 'hiddendim': 256, 'numclasses': 1000, 'numlstms': 2}, 'training': {'train': True, 'epochs': 1, 'startepoch': 0, 'statsfrequency': 100, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/trn_1000.txt', 'padding': 30, 'learningrate': 0.001, 'momentum': 0.9, 'weightdecay': 0.003, 'save_prefix': 'weights/tv_word_2000'}, 'validation': {'validate': True, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/val_1000.txt', 'padding': 60, 'saveaccuracy': True}, 'test': {'test': False, 'data_root': 'LRW1000_Public/images', 'index_root': 'LRW1000_Public/info/tst_1000.txt', 'padding': 60, 'saveaccuracy': True}}
matched keys: 431
index file: LRW1000_Public/info/trn_1000.txt
num of pinyins: 1000
num of data: 603097
max video length 30
index file: LRW1000_Public/info/val_1000.txt
num of pinyins: 1000
num of data: 63237
max video length 51
options["training"]["startepoch"], options["training"]["epochs"]: 0 1
Starting training...
Iteration: 00000000,Elapsed Time: 00 hrs, 00 mins, 13 secs,Estimated Time Remaining: 2277 hrs, 40 mins, 42 secs,Loss:3.082460403442383
Iteration: 00000200,Elapsed Time: 00 hrs, 00 mins, 22 secs,Estimated Time Remaining: 18 hrs, 47 mins, 20 secs,Loss:4.493927001953125
Iteration: 00000400,Elapsed Time: 00 hrs, 00 mins, 31 secs,Estimated Time Remaining: 13 hrs, 07 mins, 18 secs,Loss:4.264379501342773
Iteration: 00000600,Elapsed Time: 00 hrs, 00 mins, 40 secs,Estimated Time Remaining: 11 hrs, 16 mins, 48 secs,Loss:5.106860160827637
Iteration: 00000800,Elapsed Time: 00 hrs, 00 mins, 49 secs,Estimated Time Remaining: 10 hrs, 22 mins, 03 secs,Loss:6.046342849731445
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\envs\py36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Git_Lip\Lipreading-DenseNet3D\main.py", line 119, in run
    trainer(model, epoch)
  File "E:\Git_Lip\Lipreading-DenseNet3D\training.py", line 83, in __call__
    for i_batch, sample_batched in enumerate(self.trainingdataloader):
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\py36\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Git_Lip\Lipreading-DenseNet3D\data\dataset.py", line 42, in __getitem__
    temporalvolume = bbc(vidframes, self.padding, self.augment)
  File "E:\Git_Lip\Lipreading-DenseNet3D\data\preprocess.py", line 41, in bbc
    ])(vidframes[i])
  File "D:\Anaconda3\envs\py36\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torchvision\transforms\transforms.py", line 127, in __call__
    return F.to_pil_image(pic, self.mode)
  File "D:\Anaconda3\envs\py36\lib\site-packages\torchvision\transforms\functional.py", line 131, in to_pil_image
    raise ValueError('pic should be 2/3 dimensional. Got {} dimensions.'.format(pic.ndim))
ValueError: pic should be 2/3 dimensional. Got 0 dimensions.

**Comment by Fengdalu** [comment]
Please check the downloaded dataset, if there are any problems, please email me.

**Comment by PingYufeng** [comment]
您好，目前遇到了有待解决几个问题和想请教您：
1、使用中科院杨双博士提供的数据集LRW-1000在解压时出现了错误，part.tar.01部分数据损失。另有检查出5张图片损坏，请见附件。
    


2、我取其中的部分（从‘对’到‘展开’的标签）训练集、验证集、测试集进行成功训练时，发现得出的结果达不到预期期望。
参数配置如下：
title = "LipReading PyTorch"
[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "0"
loadpretrainedmodel = true
random_seed = 55
pretrainedmodelpath = 'weights/lrw1000_34.pt'


[input]
batchsize = 16
numworkers = 8
shuffle = true


[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
numclasses = 1000
numlstms = 2


[training]
train = true
epochs = 10
startepoch = 0
statsfrequency = 100 
data_root = 'LRW1000_Public/images'
index_root = 'LRW1000_Public/lables/trn/[dui_to_zhankai)Trn.txt'
padding = 30
learningrate = 1e-3
momentum = 0.9
weightdecay = 0.003
save_prefix = "weights/tv_word_100"


[validation]
validate = false
data_root = 'LRW1000_Public/images'
index_root = 'LRW1000_Public/lables/val/[dui_to_zhankai)Val.txt'
padding = 60
saveaccuracy = true


[test]
test = false
data_root = 'LRW1000_Public/images'
index_root = 'LRW1000_Public/lables/tst/[dui_to_zhankai)Tst.txt'
padding = 60
saveaccuracy = true



训练结果：loss已近平滑参数为1了。但感觉有点问题。
    


测试结果：
count[0:]:[ 669. 1289. 1650. 1918. 2094. 2243. 2374. 2493. 2629. 2760. 2899. 3047.
 3153. 3207. 3300. 3360. 3407. 3446. 3516. 3577. 3740. 3886. 3939. 4080.
 4143. 4190. 4269. 4308. 4355. 4418. 4468. 4509. 4553. 4597. 4664. 4680.
 4701. 4732. 4749. 4771. 4811. 4840. 4873. 4934. 4952. 5000. 5017. 5032.
 5068. 5089. 5120. 5158. 5184. 5237. 5259. 5289. 5304. 5324. 5358. 5390.
 5417. 5429. 5444. 5483. 5493. 5513. 5567. 5587. 5615. 5634. 5667. 5678.
 5710. 5734. 5757. 5790. 5808. 5843. 5866. 5898. 5935. 5944. 5967. 5984.
 6008. 6043. 6100. 6128. 6155. 6228. 6253. 6273. 6300. 6357. 6440. 6481.
 6521. 6583. 6604. 6687. 6699. 6725. 6775. 6802. 6859. 6898. 6938. 6957.
 6996. 7022. 7042. 7068. 7090. 7117. 7136. 7159. 7173. 7211. 7234. 7258.
 7277. 7320. 7352. 7393. 7414. 7442. 7475. 7494. 7513. 7526. 7544. 7562.
 7583. 7614. 7632. 7686. 7717. 7740. 7750. 7765. 7783. 7810. 7827. 7843.
 7859. 7871. 7883. 7892. 7905. 7915. 7923. 7933. 7949. 7960. 7968. 7977.
 7999. 8020. 8035. 8047. 8075. 8108. 8145. 8159. 8185. 8199. 8212. 8234.
 8248. 8256. 8261. 8275. 8290. 8303. 8308. 8322. 8335. 8347. 8366. 8379.
 8403. 8428. 8447. 8464. 8484. 8497. 8505. 8524. 8542. 8559. 8569. 8594.
 8609. 8619. 8633. 8638. 8658. 8667. 8673. 8694. 8702. 8719. 8734. 8742.
 8755. 8758. 8764. 8776. 8790. 8802. 8816. 8837. 8844. 8857. 8869. 8887.
 8896. 8909. 8917. 8936. 8952. 8965. 8993. 9007. 9015. 9044. 9059. 9068.
 9079. 9087. 9090. 9103. 9115. 9122. 9133. 9151. 9165. 9177. 9187. 9201.
 9208. 9219. 9228. 9238. 9244. 9254. 9260. 9273. 9333. 9343. 9363. 9371.
 9380. 9393. 9403. 9409. 9424. 9436. 9445.]
input.size(0): 13, num_samples: 9453
i_batch/tot_batch:590/591,corret/tot:669.0/9453,current_acc:0.0707711837511901
---------------------
Top #     |  Accuracy
0         |0.0707711837511901
1         |0.1363588278853274
2         |0.17454776261504285
3         |0.2028985507246377
4         |0.22151697873690893
---------------------



3、在统计准确率时，不是很明白count[p:]的原理。请问能否简单阐述下该模型测试评估准确率的方法吗
validation.py
for i in range(input.size(0)):
    p = list(argmax[i]).index(labels[i])
   count[p:] += 1





期待您的解答，感谢。

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




------------------ 原始邮件 ------------------
发件人: "Dalu Feng"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 中午11:41
收件人: "Fengdalu/Lipreading-DenseNet3D"<Lipreading-DenseNet3D@noreply.github.com>;
抄送: "沉忌"<2554550408@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Fengdalu/Lipreading-DenseNet3D] 请问CUDA out of memory && ValueError: pic should be 2/3 dimensional. Got 0 dimensions.出错 (#4)




Closed #4.
