### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by cassiemxtt** [Fengdalu/Lipreading-DenseNet3D#5]
Could you please tell me your structure  of your  train data?
Thank you very much!

**Comment by Bryce1010** [comment]
+1

**Comment by Fengdalu** [comment]
> Could you please tell me your structure of your train data?
> Thank you very much!

Details are described  in Data_Annotation.txt in LRW1000 dataset

**Comment by sunnymoon155** [comment]
@cassiemxtt @Bryce1010 Did u guys get the structure of the dataset?
