### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by sunnymoon155** [Fengdalu/Lipreading-DenseNet3D#7]
Hi, thanks for the repo. I'd like to train this on my own datasets, and could your please show me the format of the datasets?
for example the train txt file trn_1000.txt or tst_1000.txt test file.

**Comment by Fengdalu** [comment]
The annotation format is in our published LRW-1000 dataset. You can apply it via http://vipl.ict.ac.cn/view_database.php?id=14
