### ISSUE TITLE
words list

### ISSUE THREAD

**Issue by marziehoghbaie** [Fengdalu/Lipreading-DenseNet3D#8]
Hi, 
I used your model for lip reading a short unseen video and the output is a tensor of numbers in the following format:
tensor([[[ -8.0249,  -3.9531,  -5.8029,  ..., -10.0934, -11.3949, -10.5158],
         [ -8.2467,  -3.9986,  -5.5527,  ..., -10.2224, -11.8399, -10.9000],
         [ -8.3477,  -3.9405,  -5.4165,  ..., -10.2591, -11.7992, -10.9858],
         ...,
         [ -7.8587,  -3.9410,  -4.3205,  ...,  -9.5626, -10.5396,  -9.8517],
         [ -7.7610,  -4.1559,  -4.3000,  ...,  -9.2372, -10.2023,  -9.4559],
         [ -7.4791,  -4.3723,  -4.2590,  ...,  -8.7825,  -9.6632,  -8.9603]]],
       device='cuda:0')

how can I convert it to the list of probable words?
TNX in advance.

**Comment by Fengdalu** [comment]
Hi, the word list is in the info folder of our released lrw1000 dataset, you can write an additional script to get the word.

**Comment by marziehoghbaie** [comment]
TNX, There is another question, the model output is kind of weird, does it return 1000 probability fro each frame?

**Comment by Fengdalu** [comment]
> TNX, There is another question, the model output is kind of weird, does it return 1000 probability fro each frame?

Yes, The probability of a single sample is the average of each frames .
